
APP_NAME        = a

MALLOC_SIZE     = 0x00000000
STACK_SIZE      = 0x00004000
DATSEG_SIZE     = 0x00004000

include ../AppCommon.mak

##
##    Dependencies
##

#API_LIBS = ../ApiLib/apilib.a
#a.hrb         : a.obj         ${API_LIBS}
